#!/bin/sh
export DISPLAY=$DISPLAY;
export XAUTHORITY=/home/tonk/.Xauthority
UNSPAWNED=0
if zenity --question --text="Really open unspawned browser?" --ok-label="Yes, dammit!" --cancel-label="No way!" ; then
	if zenity --question --text="Behaving like a moron?" --ok-label="Go on and stop me!" --cancel-label="I understand the risk!" ; then
		zenity --info --text="Like your style." &
		sleep 2
		exit
	else
		zenity --info --text="Might like to close this next window in a hurry." &
		sleep 2
		UNSPAWNED=1
	fi
fi
if [[ $UNSPAWNED = "1" ]] ; then
	sudo su tonk -c "/usr/bin/google-chrome-stable $@"
	#su tonk -c "DISPLAY=$DISPLAY eog /home/amsc/canoe.jpg"
else
	sudo strafe start browser
fi
