#!/bin/sh
IF=eth0
. /etc/profile.d/hosts.sh
. bridge.sh
setup
work
route del default
ping="ping -c1 -W1"
for ip in $rth0 ; do
	#dhclient -i eth0 2>&1 >/tmp/${ip}.start &
	ADDR=$(echo $ip | cut -f1-3 -d.).2
	if ifconfig $IF $ADDR && $ping $ip && route add default gw $ip ; then break ; fi
	#killall dhclient
done
ifconfig $IF
default-route.sh
$ping $tplink 
$ping $bthub  
